project:
  type: website

website:
  title: "Maximiliano Alvarez"
  navbar:
    left:
      - href: blog.qmd
        text: Blog
  search: true
  open-graph: true

format:
  html:
    theme: cosmo

execute:
  freeze: true
  